SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Drivers](
	[DriverID] [int] NOT NULL,
	[Nome] [varchar](100) NULL,
	[CNH] [varchar](200) NULL,
	[Endereço] [varchar](200) NULL,
	[Contato] [varchar](50) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Drivers] ADD PRIMARY KEY CLUSTERED 
(
	[DriverID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
